# Dark Chatbot Builder Pro - Netlify Configuration
# Optimized for PWA deployment with enhanced performance

[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "18"

# URL redirects and rewrites for SPA routing
[[redirects]]
  from = "/app/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/builder/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/editor/*"
  to = "/index.html"
  status = 200

# SEO redirects
[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 301

[[redirects]]
  from = "/robots"
  to = "/robots.txt"
  status = 301

# Security redirects
[[redirects]]
  from = "/.well-known/security"
  to = "/.well-known/security.txt"
  status = 301

# Force HTTPS
[[redirects]]
  from = "http://darkchatbotbuilder.com/*"
  to = "https://darkchatbotbuilder.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.darkchatbotbuilder.com/*"
  to = "https://darkchatbotbuilder.com/:splat"
  status = 301
  force = true

# Asset optimization
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Edge functions (if needed in future)
[dev]
  framework = "#static"
  command = "python -m http.server 8000"
  targetPort = 8000
  port = 8888
  autoLaunch = true

# Custom headers for enhanced security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), bluetooth=()"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=604800"
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000"

# Forms handling (if contact forms are added later)
[build.processing.forms]
  endpoint = "/contact"

# Performance optimizations
[build.processing.skip_processing]
  css = false
  js = false
  html = false
  images = false

# Branch deploys
[context.production]
  command = "echo 'Production deployment'"

[context.deploy-preview]
  command = "echo 'Deploy preview'"

[context.branch-deploy]
  command = "echo 'Branch deployment'"
